version: '3.9'
services:
  angular-front:
    container_name: front-myshop
    image: nginx:latest
    ports:
      - 80:80
      - 4200:4200
    volumes:
      - ./docker-files/nginx/conf:/etc/nginx/conf.d/:ro
      - ./docker-files/nginx/ssl:/etc/nginx/ssl/:ro
      - ./../frontend/dist/frontend-angular:/usr/share/nginx/html/
    networks:
      - network-1


  backend-postgres:
    container_name: myshop-pgserver-container
    image: postgres:15-alpine
    networks:
      - network-1

    ports:
      - "5432:5432"
    volumes:
      - ./docker-files/postgres-db-data:/var/lib/postgresql/data
      - ./docker-files/schema-create:/docker-entrypoint-initdb.d
      #      - /opt/postgres-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: rootroot


  backend:
    container_name: myshop-backend-container
    image: myshop-backend-image
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - network-1
    ports:
      - "8081:8081"
      - "8082:8082"
    restart: always
    depends_on:
      backend-postgres:
        condition: service_started
      keycloak-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rootroot


  bff:
    container_name: myshop-bff-container
    image: myshop-bff-image
    build:
      context: ./../bff/
      dockerfile: Dockerfile
    networks:
      - network-1
    ports:
      - "8902:8902"
      - "8901:8901"


  keycloak-server:
    container_name: keycloak-server-container
    image: quay.io/keycloak/keycloak:18.0.0
    command:
      - start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ulrikeFraupe2711-
      KC_HOSTNAME: myshopapp.kyiv.ua
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/data/ssl/myshopapp-kyiv-ua.cer
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/data/ssl/myshopapp-kyiv-ua.pkcs8
    ports:
      - "8443:8443"
      - "8080:8080"
    restart: always
    volumes:
      - ./docker-files/keycloak/ssl:/opt/keycloak/data/ssl
      - ./docker-files/keycloak/realm-export:/opt/keycloak/data/import
    networks:
      - network-1

networks:
  network-1: