## Начинаем с базового образа Keycloak
#FROM quay.io/keycloak/keycloak:18.0.0
#
## Копируем SSL-сертификаты и ключи в контейнер
#COPY ./docker-files/keycloak/ssl/myshop_keycloak_ssl.cer /opt/keycloak/data/ssl/myshop_keycloak_ssl.cer
#COPY ./docker-files/keycloak/ssl/myshop_keycloak_ssl.pkcs8 /opt/keycloak/data/ssl/myshop_keycloak_ssl.pkcs8
#
## Опционально: Копировать файл экспорта области в контейнер
## COPY ./docker-files/keycloak/realm-export/realm-export.json /opt/keycloak/data/import/realm-export.json
#
## Задаем переменные окружения (если нужно, можно добавить больше)
#ENV KEYCLOAK_ADMIN=admin
#ENV KEYCLOAK_ADMIN_PASSWORD=admin
#ENV KC_HOSTNAME=localhost
#ENV KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/data/ssl/myshop_server_ssl.cer
#ENV KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/data/ssl/myshop_server_ssl.pkcs8
#
#CMD ["kc.sh", "start-dev", "--https-certificate-file=/opt/keycloak/data/ssl/myshop_server_ssl.cer", "--https-certificate-key-file=/opt/keycloak/data/ssl/myshop_server_ssl.pkcs8"]
#

FROM quay.io/keycloak/keycloak:18.0.0 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
#ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
#RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=localhost" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:18.0.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

COPY ./docker-files/keycloak/ssl/myshop_keycloak_ssl.cer /opt/keycloak/data/ssl/myshop_keycloak_ssl.cer
COPY ./docker-files/keycloak/ssl/myshop_keycloak_ssl.pkcs8 /opt/keycloak/data/ssl/myshop_keycloak_ssl.pkcs8
ENV KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/data/ssl/myshop_server_ssl.cer
ENV KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/data/ssl/myshop_server_ssl.pkcs8



# change these values to point to a running postgres instance
#ENV KC_DB=postgres
#ENV KC_DB_URL=<DBURL>
#ENV KC_DB_USERNAME=<DBUSERNAME>
#ENV KC_DB_PASSWORD=<DBPASSWORD>
#ENV KC_HOSTNAME=localhost
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]