version: '3.9'
services:
  #  angular-front:
  #    container_name: angular-front-container
  #    image: angular-front-image
  #    networks:
  #      - network-1
  #    ports:
  #      - "4200:80"
  angular-front:
    container_name: angular-front-container
    image: nginx:latest
    networks:
      - network-1
    ports:
      - "4200:4200"
    volumes:
      - ./front-certs:/etc/nginx/certs

  backend-postgres:
    container_name: myshop-pgserver-container
    image: postgres
    networks:
      - network-1
    ports:
      - "5432:5432"
    volumes:
      - c:\11\docker-backend\data:/var/lib/postgresql/data
      - ./schema-create:/docker-entrypoint-initdb.d
      #      - /opt/postgres-db-data:/var/lib/postgresql/data
      #      - c:\11\docker-backend\sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: rootroot
  
  
  backend:
    container_name: myshop-backend-container
    image: myshop-backend-image
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - network-1
    ports:
      - "8081:8081"
    depends_on:
      backend-postgres:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backend-postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rootroot


  bff:
    container_name: myshop-bff-container
    image: myshop-bff-image
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - network-1
    ports:
      - "8902:8902"

  # sepatare db-server for keycloak
  #  keycloak-db-server:
  #    container_name: keycloak-postgres-container
  #    image: postgres:15
  #    #    expose:
  #    #      - "5555" # Publishes 5433 to other containers but NOT to host machine
  #    ports:
  #      - '5555:5432'
  #    #    command: -p 5555
  #
  #
  #    volumes:
  #      - C:/11/keycloak-docker/db:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_DB: keycloak21
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: postgres
  #
  #    networks:
  #      - network-1

  keycloak-server:
    container_name: keycloak-server-container
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      #KC_DB: h2
      #      KC_DB_URL_DATABASE: keycloak21
      #      KC_DB_URL_HOST: keycloak-db-server
      #      KC_DB_URL_PORT: 5555
      #      KC_DB_USERNAME: postgres
      #      KC_DB_PASSWORD: postgres
      #      KC_DB_SCHEMA: public
      KC_HTTPS_CERTIFICATE_FILE: /var/lib/keycloak/ssl/localhost.cer
      KC_HTTPS_CERTIFICATE_KEY_FILE: /var/lib/keycloak/ssl/localhost.pkcs8
      KEYCLOAK_IMPORT: /var/lib/keycloak/data/import/realm-export.json
    restart: always
    ports:
      #      - "8111:8080"
      - "8443:8443"
    #    depends_on:
    #      - keycloak-db-server
    volumes:
      - ./kc-imports/:/var/lib/keycloak/ssl
      - ./kc-imports:/var/lib/keycloak/data/import
    networks:
      - network-1
networks:
  network-1:
