FROM gradle:7.5.1-jdk17-alpine as build
WORKDIR /app
COPY --chown=gradle:gradle . /app

RUN gradle build --no-daemon

FROM openjdk:17

EXPOSE 8902
EXPOSE 8901


COPY --from=build /app/build/libs/myshop-bff-0.0.1.jar /app/app-bff.jar
ENV KEYCLOAK_SECRET=DJpEuC02LXbKC2jdrozBIbAZyejaUcM5

ENTRYPOINT ["java", "-jar", "/app/app-bff.jar", "--spring.profiles.active=dev"]