name: "test run command on remote server3"
on:
  push:
    branches: [ "main" ]
jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: run command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            echo 'Hello world';